blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/YOUR_USERNAME/inbox-triage-extension/blob/main/README.md
    about: Check the README and docs folder for setup instructions and usage guides
  - name: Chrome AI API Documentation
    url: https://developer.chrome.com/docs/ai/built-in
    about: Official Chrome Built-in AI APIs documentation

